### ISSUE TITLE
include path error

### ISSUE THREAD

**Issue by wanggaohang** [Microsoft/multiverso#10]
after builder as README said
run ./multiverso_server 
ERROR:
error while loading shared libraries: libzmq.so.5: cannot open shared object file: No such file or directory

**Comment by chivee** [comment]
please make sure that your zmq library has been compiled.

**Comment by feiga** [comment]
@wanggaohang If you follow the step as README to build, the shared object file libzmq.so.5 should be in folder ```$multiverse_folder/third_party/lib```. You can follow this [guild](http://www.cnblogs.com/smartvessel/archive/2011/01/21/1940868.html) to solve this problem. Hope this helps.
