### ISSUE TITLE
install on OS X

### ISSUE THREAD

**Issue by dselivanov** [Microsoft/multiverso#11]
`make all -j4` produce following:
> find: /src/multiverso: No such file or directory
find: /src/multiverso_server: No such file or directory
find: /src/multiverso: No such file or directory
find: /src/multiverso_server: No such file or directory
mkdir -p /lib
mkdir: /lib: Permission denied
find: /src/multiverso: No such file or directory
make: *** [/lib] Error 1

I'm not an expert in Makefiles, but why it try install into `/src/multiverso_server`?

**Comment by chivee** [comment]
the compiler is trying to locate the source in the /src/multiverso. which will be compile into .o file in the src folder, and link to the lib file later on.

the log shows that you don't have the write permission of your folder.

try to grant the whole folder the permission with following code:
                   chmod 755  -R .

**Comment by dselivanov** [comment]
Yes, I understood that. Is is possible to configure to not use `/src/...` and install to somewhere at home dir?

**Comment by chivee** [comment]
we'll adjust the Makefile. thanks for your suggestion. :)

**Comment by dselivanov** [comment]
thanks, that will be awesome! 
feel free to close after that =)
