### ISSUE TITLE
What's the clock means in BSP (max_delay=0)? 

### ISSUE THREAD

**Issue by xn0507** [Microsoft/multiverso#115]
In multiverso document, it says:
BSP (max_delay=0): All worker processes are barriered forcibly at the end of a clock.

What's the "clock" actually means in multiverso? Some mini-batches or a period of time?

**Comment by chivee** [comment]
sorry for the delayed documents, the logic "clock" has been removed in the latest version. you could using  MV_SetFlag("sync", true); [latest docs](https://github.com/Microsoft/multiverso/wiki/Multiverso-document) to perform synced-SGD.

**Comment by xn0507** [comment]
Thanks for your answer.
But, can the latest multiverso support SSP and ASP? 
Can we use the SSP or ASP mode by set the value of "max_delay " as before?
@chivee

**Comment by feiga** [comment]
Latest Multiverso support both sync and async training. The config "max_delay" is deprecated.

**Comment by xn0507** [comment]
Thanks. But, how to set the mini-batch size in the latest Multiverso? I think a data block means a mini-batch samples, is it right? @feiga @chivee

**Comment by feiga** [comment]
You can set any numbers as the way you set in single machine setting.
