### ISSUE TITLE
Multiverso support  SSP?

### ISSUE THREAD

**Issue by yuandy** [Microsoft/Multiverso#136]
I see multiverso only support ASP and BSP, it support ssp?

**Comment by chivee** [comment]
Hi Yuandy,

SSP didn't supported by multiverso yet

**Comment by apir8181** [comment]
Why didn't supported SSP? It's really common to have a large cluster and some machines are stragglers.
It should be easy to implement a SSP server, just by modifying SyncServer in server.cpp.
