### ISSUE TITLE
cmake error

### ISSUE THREAD

**Issue by yttdebaba2** [Microsoft/Multiverso#137]
I want to install word-embedding on linux.

I enter the following lines:
`cd multiverso/Applications/WordEmbedding    `    

`cmake CMakeLists.txt`
and the error occur:
`CMake Error at CMakeLists.txt:22 (add_executable):`
`  Cannot find source file:`

`    //src`

`  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp`
`  .hxx .in .txx`

Any help would be appreciate.

**Comment by chivee** [comment]
`sudo apt-get install libopenmpi-dev openmpi-bin build-essential cmake git
git clone https://github.com/Microsoft/multiverso.git && cd multiverso
mkdir build && cd build
cmake .. && make && sudo make install`

on the root folder will make all the applications
