### ISSUE TITLE
Does Multiverso support concurrent message handling in server table?

### ISSUE THREAD

**Issue by apir8181** [Microsoft/Multiverso#138]
I implement a new table and create a bunch of client threads to send the GET and ADD operations. I suppose the table can concurrently handle multiple GET and ADD ops. No matter how many threads I create, I can only observe "200% CPU usage" in Linux top command. I guess "100%" is on client side, and another "100%" is on server side. 

I also notice "opm_threads" keyword exists in the API-document. But I failed to setup this variable and get a fatal error in FlagRegister::SetFlagIfFound method.

Does Multiverso support concurrent message handling in server table? If it does, how to enable concurrent server side processing?

**Comment by feiga** [comment]
No, the table can't concurrently handle multiple Get and Add. The message are processed one by one. The Get and Add interface are not thread-safe -- you shall care about concurrent issues in user side.

For the CPU usage, how many cores does your machine have?

The option "omp_threads" specify the number of omp thread used by Multiverso. The omp is mainly used in server side when server handle workers' request. For example, when handling one Add request, multiple threads is used to speedup. But every time only one message is processed.

**Comment by apir8181** [comment]
Thanks for reply. I come up to this question when I trying to implement an algorithm, which requires lots of computation on server side. 

Although my machine have 8 cores, the implementation's server table ProcessGet and ProcessAdd are just serial. This should be the bottleneck.

Since the table can't concurrently handle multiple Get and Add. I think I should make each Get and Add heavier and use multi-threads to handle each request.

**Comment by feiga** [comment]
Yes, please use multi-threads to handle each request.
