### ISSUE TITLE
What does the related include and lib file mean？

### ISSUE THREAD

**Issue by edwardnevermind** [Microsoft/multiverso#14]
![image](https://cloud.githubusercontent.com/assets/5945399/11261817/5916210a-8eb3-11e5-983a-b514b8785ffe.png)

**Comment by chivee** [comment]
when you install both ZeroMQ and MSMPI, you can either:
    1) change the include path and linking path in your Visual Studio solution
or
    2) copy the ``` include ``` and ```lib``` folder of ZMQ and MSMPI,  into ```third_party``` folder.

**Comment by edwardnevermind** [comment]
Thanks a lot!!
