### ISSUE TITLE
High cpu usage of communicator

### ISSUE THREAD

**Issue by apir8181** [Microsoft/Multiverso#142]
To better tune my application, I set name for every threads by calling _pthread\_setname\_np_ API in linux. I found that high cpu usage for Multiverso's Communicator(subclass of Actor) thread. Here is a snapshot provided by htop.
![selection_010](https://cloud.githubusercontent.com/assets/1999813/23025911/63e1dc7a-f49a-11e6-8da1-6385b9c10ff6.png)

I notice some code in src/communicator.cpp. According to this code, communicator always call non-blocking send and receive. I think this is the result of high cpu usage.
```case NetThreadLevel::THREAD_SERIALIZED: {

    MessagePtr msg;
    while (mailbox_->Alive()) {
      // Try pop and Send
      if (mailbox_->TryPop(msg)) {
        ProcessMessage(msg);
      }
      // Probe and Recv
      size_t size = net_util_->Recv(&msg);
      if (size > 0) LocalForward(msg);
      CHECK(msg.get() == nullptr);
      net_util_->Send(msg);
    }
    break;
  }
```

This "spin lock" design is great. But most applications won't call send/recv thousand or millions times in a second, which means  a cpu computation resource is wasted. Why not sleep communicator for a little while when no send/recv calls?

**Comment by feiga** [comment]
Communicator only uses one thread. Usually it's not a big overhead for a multi-cores machine. But you could add Sleep in the code for your usage.

**Comment by apir8181** [comment]
It's pretty reasonable. I think my problem is solved.
