### ISSUE TITLE
Several questions about the communication between server and worker

### ISSUE THREAD

**Issue by etali** [Microsoft/multiverso#15]
Your work is really awesome, and I have learn a part of the project, but might not understand it very well.
I have several questions about the communication between server and worker as follows.

1. It seem that servers will not communicate with each other? Do the workers determine from which server to pull/push the parameters?
2. Why you design the structure "Table"? It seems that parameters data can be consisted of "Rows".
    + Does a whole table should be stored in a single server? There is not intersection between different servers?
    + When will we need to create multiple "Tables"?

Thank you so much.

**Comment by chivee** [comment]
Hi Yitan,

It's true that different sever will not communicate with each other for the reason that the parameter are not duplicated in each server. The workers didn't have to determine which server should pull/push to.

the table is a logic unit for some algorithms. the actual process unit is an row, which will store in different servers ( if you have).

**Comment by etali** [comment]
Hi Haiwei,

Thank you for your reply.

**Comment by etali** [comment]
Hi Haiwei,

Thank you for your reply.
