### ISSUE TITLE
Server::Process_EndTrain overflow?

### ISSUE THREAD

**Issue by xdlxl** [Microsoft/multiverso#16]
void Server::Process_EndTrain(std::shared_ptr<MsgPack> msg_pack)
    {
        MsgType msg_type;
        MsgArrow arrow;
        int src, dst;
        msg_pack->GetHeaderInfo(&msg_type, &arrow, &src, &dst);
        clocks_[src] = 1 << 31;
in this place ,clocks_ is vector<int>,so after bit manipulation clocks_[src] will become INT_MIN;so after one worker end train,other workers will be hanging in config.max_delay >=0. Will this be a problem?

**Comment by feiga** [comment]
Yes. It should be a mistake. I think it is intending to assign a large enough number to the clock. Change 31 to 30 should be OK, although it's a little tricky. Thanks for reporting this.
