### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [Microsoft/multiverso#2]
I would like to point out that identifiers like "[`_MULTIVERSO_BARRIER_H_`](https://github.com/Microsoft/multiverso/blob/250144cc88c77842b3217e5b498b8813b8e72400/include/multiverso/barrier.h#L1)" and "[`_MULTIVERSO_SERVER_H_`](https://github.com/Microsoft/multiverso/blob/84ee9a7149095820337bf5cfb505aaea04512214/include/multiverso/server.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by chivee** [comment]
Thanks for your suggestion.

We will adjust the macros.

**Comment by elfring** [comment]
Would it be better to leave this issue open until the affected implementation details will be fixed?

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/Microsoft/multiverso/commit/be1995bb0647a8be9900d69e744347391afb114b "Deletion of a few underscores").
