### ISSUE TITLE
how was the failure handing in server side?

### ISSUE THREAD

**Issue by YongCHN** [Microsoft/multiverso#3]
if i use the mpi, how does multiverse handles the failure of the server? does it support the failover?

**Comment by chivee** [comment]
Considering MPI mechanism, fail tolerance is an important feature for us. in the current version, we don't offer an API for checkpoint.  you can do an quick hacking on the client side( dumping whole parameter for couples of EPOCH). we will add this feature soon.

**Comment by YongCHN** [comment]
how about the zeromq? was the failover supported? thanks.

**Comment by feiga** [comment]
Not support yet.

**Comment by chivee** [comment]
i think it necessary to add failure recovery, lets' remain this to open.
