### ISSUE TITLE
Remove unnecessary null pointer checks

### ISSUE THREAD

**Issue by elfring** [Microsoft/multiverso#4]
[An extra null pointer check is not needed in functions](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for NULL before delete p?") like the following.
* [Aggregator](https://github.com/Microsoft/multiverso/blob/21a33fd80b8bb39f01976a38b2d2e084ad6a8cb2/src/multiverso/aggregator.cpp#L33 "destructor for Aggregator")
* [Communicator](https://github.com/Microsoft/multiverso/blob/21a33fd80b8bb39f01976a38b2d2e084ad6a8cb2/src/multiverso/communicator.cpp#L54 "destructor for Communicator")
* [Table](https://github.com/Microsoft/multiverso/blob/21a33fd80b8bb39f01976a38b2d2e084ad6a8cb2/src/multiverso/table.cpp#L41 "destructor for Table")

**Comment by feiga** [comment]
Done, thanks.

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/Microsoft/multiverso/commit/f2fa8a1e103ff5ea22c9affe03236d225e89cad7 "Deletion of three pointer checks").

**Comment by elfring** [comment]
[Extra null pointer checks are not needed](https://isocpp.org/wiki/faq/freestore-mgmt#delete-handles-null "Do I need to check for null before delete p?") also in [the destructor for the class “AllreduceEngine”](https://github.com/Microsoft/Multiverso/blob/ae1cb7e7f47d6bda1e5285bc419a7c6225b865ce/src/net/allreduce_engine.cpp#L25 "Update candidate: Destructor for AllreduceEngine").
