### ISSUE TITLE
Use of angle brackets around file names for include statements

### ISSUE THREAD

**Issue by elfring** [Microsoft/multiverso#6]
Would you like to [replace any double quotes](https://github.com/Microsoft/multiverso/blob/964088189083a967971a36abba677635dec175e3/include/multiverso/multiverso.h#L15 "Check header file inclusion style.") by [angle brackets around file names for include statements](http://stackoverflow.com/questions/21593/what-is-the-difference-between-include-filename-and-include-filename "What is the difference between #include <filename> and #include “filename”?")?

**Comment by chivee** [comment]
i think it is convention to using double quotes for the user defined source flies, i cannot understand the necessary that using angle brackets instead.

**Comment by elfring** [comment]
I suggest to reconsider the consequences of [the following wording](http://c0x.coding-guidelines.com/6.10.2.html "Source file inclusion") from [the section "16.2 Source file inclusion"](http://open-std.org/jtc1/sc22/wg21/docs/papers/2013/n3797.pdf "C++ working draft") in the standard specification for the programming language "C++".
```
…
The named source file is searched for in an implementation-defined manner. If this search is not supported, or if the search fails, the directive is reprocessed as if it read

#include <h-char-sequence> new-line
…
```

* How do you think about to avoid "a duplicated file search" here?
* Would you like to [restrict the searched directories](https://gcc.gnu.org/onlinedocs/cpp/Include-Syntax.html "Include syntax description") for header files of your software?

**Comment by chivee** [comment]
hi elfring,
thanks a lot for your feedback, after the discussion with the team, we decide to keep the [coding style](https://google.github.io/styleguide/cppguide.html#Names_and_Order_of_Includes). Nevertheless, we still learn a lot from you. thanks for your suggestion.
