### ISSUE TITLE
Encountering a problem when using array table with small sizes

### ISSUE THREAD

**Issue by you-n-g** [Microsoft/Multiverso#69]
I'm using a array table with size == 1.
Because multiverso  checks that `size_ > MV_NumServers()`
So I get errors below.
```
[INFO] [2016-05-29 14:20:24] multiverso MPI-Net is initialized under MPI_THREAD_SERIALIZED mode.
[INFO] [2016-05-29 14:20:24] All nodes registered. System contains 1 nodes. num_worker = 1, num_server = 1
[INFO] [2016-05-29 14:20:24] Create a async server
[INFO] [2016-05-29 14:20:24] Rank 0: Zoo start sucessfully
[FATAL] [2016-05-29 14:20:25] Check failed: size_ > MV_NumServers() at /home/xiaoyang/repos/multiverso/src/table/array_table.cpp, line 14 .
```

**Comment by chivee** [comment]
I'm not quite sure why should using this `CHECK`

**Comment by huxuan** [comment]
Xiang Li, @implus ,also reported this bug when he try to sync a one-size parameter. He may come to confirm later.

**Comment by implus** [comment]
`[INFO][2016-05-31 19:53:03] All nodes registered. System contains 2 nodes. num_worker = 2, num_server = 2`
`[FATAL] [2016-05-31 19:53:09] Check failed: size_ > MV_NumServers()at /home/xiangli/multiverso/src/table/array_table.cpp, line 14 .`
`[FATAL] [2016-05-31 19:53:09] Check failed: size_ > MV_NumServers()at /home/xiangli/multiverso/src/table/array_table.cpp, line 14 .`
`[MSRAML-GPU02:22870] *** Process received signal ***`
`[MSRAML-GPU02:22871] *** Process received signal ***` 

when I use tablehandler with size 1, that problem occurs. I modify size to 3 by padding 2 useless elements, it's OK.
