### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by wanggaohang** [Microsoft/multiverso#9]
zmq.hpp：No such file or directory
 #include "zmq.hpp"

**Comment by fiberleif** [comment]
maybe you need to download the C++ wrapper of ZeroMQ [zmq.hpp](https://github.com/zeromq/cppzmq) firstly and then add the zmq.hpp path to project property->Include Directories.

**Comment by wanggaohang** [comment]
i thike the build on linux should : cd third_party; ./install.sh

**Comment by chivee** [comment]
yes it is, could you give more details of your issue? it is hard to understand what problem you are encounter?

**Comment by feiga** [comment]
@wanggaohang  Just follow the README and it should work. If you failed to include zmq.hpp, it may be caused by the failure of ```wget https://someurl/zmq.hpp``` in the script ```install.sh```.

**Comment by feiga** [comment]
@wanggaohang Thanks for pointing out this. Readme fixed.
